[book]
authors = ["Christopher Armstrong"]
multilingual = false
src = "src"
title = "Sureberus"

[output.html]
additional-css = ["src/custom.css"]

[preprocessor.test]
command = "python ./preprocessor.py"
